project/GraveBooking/Controllers/adminProfileController.cs
using GraveBooking.Models;
using GraveBooking.Services.Data;
using Microsoft.WindowsAPICodePack.Dialogs;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GraveBooking.Controllers
{
    public class adminProfileController : Controller
    {
        // GET: adminProfile
        public ActionResult updateAdminProfile()
        {
            int adminId = 0;
            if (Session["adminId"] != null)
            {
                // Value is not null, read actual value from session
                adminId = (int)Session["adminId"];
            }

            SecurityDAO dAO = new SecurityDAO();
            List<admin> adminList = dAO.fetchAdmin(adminId);
            ViewModel allmodel = new ViewModel();
            
            allmodel.admins = adminList;

            return View(allmodel);
        }

        [HttpPost]
        public ActionResult updateAdminProfile(FormCollection form)
        {
            int userId = 0;
            if (Session["adminId"] != null)
            {
                // Value is not null, read actual value from session
                userId = (int)Session["adminId"];

                SecurityDAO dAO = new SecurityDAO();


                NameValueCollection request = Request.Form;
                string name, email, phone, password;
                ViewBag.verification = false;
                if (!string.IsNullOrEmpty(request["username"]) && !string.IsNullOrEmpty(request["phone"]) && !string.IsNullOrEmpty(request["email"]))
                {
                    name = request["username"];
                    email = request["email"];
                    phone = request["phone"];
                    password = request["password"];


                    admin admin = new admin();
                    admin.adminName = name;
                    admin.adminEmail = email;
                    admin.adminPhone = phone;
                    admin.adminPassword = password;
                    SecurityDAO db = new SecurityDAO();
                    db.updateAdmin(admin, userId);
                    //ViewBag.Message = "Profile updated successfully";
                    TaskDialog.Show("Updated successfully");
                    return RedirectToAction("updateAdminProfile", "adminProfile");
                }

            }
            return View();
        }

    }
}

project/GraveBooking/Controllers/viewGraveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GraveBooking.Models;
using GraveBooking.Services.Data;
using System.Collections.Specialized;
using System.Dynamic;
using System.IO;

namespace GraveBooking.Controllers
{
    public class viewGraveController : Controller
    {
        // GET: viewGrave
        public ActionResult viewGravePost()
        {
            SecurityDAO dAO = new SecurityDAO();
            List<graveDescription> graveList = dAO.fetchgrave();
            List<admin> adminList = dAO.fetchAdmin();
            ViewModel allmodel = new ViewModel();
            allmodel.graveDescriptions = graveList;
            allmodel.admins = adminList;

            NameValueCollection request = Request.Form;
            string search;

            if (!string.IsNullOrEmpty(request["search"]))
            {
                search = request["search"];
                graveList = dAO.fetchgrave(search);
                allmodel.graveDescriptions = graveList;
                allmodel.admins = adminList;
                return View(allmodel);
            }
            return View(allmodel);
        }
        public ActionResult DisplayGraveTable()
        {
            int gId = 0;
            if (Session["adminId"] != null)
            {
                // Value is not null, read actual value from session
                gId = (int)Session["adminId"];
            }
            SecurityDAO dAO = new SecurityDAO();
            List<graveDescription> graveList = dAO.fetchgraveAsPerAdminId(gId);
            
            ViewModel allmodel = new ViewModel();
            allmodel.graveDescriptions = graveList;
            
            return View(allmodel);
        }
        public ActionResult adminProfile()
        {
            int adminId = 0;
            if (Session["adminId"] != null)
            {
                // Value is not null, read actual value from session
                adminId = (int)Session["adminId"];
            }

            SecurityDAO dAO = new SecurityDAO();
            List<graveDescription> graveList = dAO.fetchgrave();
            List<admin> adminList = dAO.fetchAdmin(adminId);
            ViewModel allmodel = new ViewModel();
            allmodel.graveDescriptions = graveList;
            allmodel.admins = adminList;

            NameValueCollection request = Request.Form;
            string search;

            if (!string.IsNullOrEmpty(request["search"]))
            {
                search = request["search"];
                graveList = dAO.fetchgrave(search);
                allmodel.graveDescriptions = graveList;
                allmodel.admins = adminList;
                return View(allmodel);
            }
            
            return View(allmodel);
        }

        public ActionResult detailsPage()
        {
            string id = Request.Url.Segments.Last();
            int gId = Convert.ToInt32(id);
         /*   if (Session["graveyardId"] != null)
            {
                // Value is not null, read actual value from session
                gId = (int)Session["graveyardId"];
            }*/
            SecurityDAO dAO = new SecurityDAO();
            dAO.DeleteTempData();
            var list1 = new List<string>();
            list1 = dAO.fetchBookedPlots(gId);
            dAO.addUnbookedPlots(list1);
            List<graveDescription> graveList = dAO.fetchgrave(gId);
            
            ViewModel allmodel = new ViewModel();
            allmodel.graveDescriptions = graveList;

            Session["graveyardId"] = gId;
            return View(allmodel);
        }

        public ActionResult OwnerInfoIntermediate()
        {
            int gId = 0;
            if (Session["graveyardId"] != null)
            {
                // Value is not null, read actual value from session
                gId = (int)Session["graveyardId"];
            }
            SecurityDAO dAO = new SecurityDAO();
            dAO.DeleteTempData();
            var list1 = new List<string>();
            list1 = dAO.fetchBookedPlots(gId);
            dAO.addUnbookedPlots(list1);
            List<Temp> plotList = dAO.showUnbookedPlots();
            ViewModel allmodel = new ViewModel();
            allmodel.Temps = plotList;
            return View(allmodel);

        }
        public ActionResult updatePlotNo()
        {
            int gId = 0;
            if (Session["graveyardId"] != null)
            {
                // Value is not null, read actual value from session
                gId = (int)Session["graveyardId"];
            }
            
            string id = Request.Url.Segments.Last();
            int pId = Convert.ToInt32(id);
            SecurityDAO dao = new SecurityDAO();
           
            int available = dao.getAvailableNoOfPlots(gId);
            int cnt = dao.getPlotCount(gId);
            dao.updateAvailablePlots(gId, cnt, available);
            dao.updatePlotNoInBooking(pId);
            dao.updatePlotNoInOwner(pId);

            return View();


        }

    }
}

project/GraveBooking/Views/viewGrave/DisplayGraveTable.cshtml
@{
    ViewBag.Title = "DisplayGraveTable";
}

<div class="card">
    <div class="card-body">
        <table class="table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th style="font-size:24px;height:80px">Graveyard Name</th>
                    <th style="font-size:24px;height:80px">Total Plots</th>
                    <th style="font-size:24px;height:80px">Available</th>
                    <th style="font-size:24px;height:80px">Price(per plot)</th>
               
                </tr>
            </thead>
            <tbody>
                @foreach (var emp in Model.graveDescriptions)
                {
                <tr>
                    <td style="font-size:20px;height:60px">@emp.graveyardName</td>
                    <td style="font-size:20px;height:60px">@emp.numberOfPlots</td>
                    <td style="font-size:20px;height:60px">@emp.availablePlot</td>
                    <td style="font-size:20px;height:60px">@emp.plotPrice</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

project/GraveBooking/Views/viewGrave/OwnerInfoIntermediate.cshtml
@model GraveBooking.Models.ViewModel
@{
    ViewBag.Title = "OwnerInfoIntermediate";
}
@Styles.Render("~/Content/css/profile")

<div class="col-12">
   
   
        <h1>Choose Plot no:</h1>
       
            <div class="container d-flex justify-content-center flex-wrap">
                @foreach (var pn in Model.Temps)
                {
                    <a class="btn-lg btn-outline-danger m-5 btn" href="@Url.Action("updatePlotNo", "viewGrave",new { id = @pn.PlotNo})">@pn.PlotNo</a>

                }
            </div>
       
   
   
</div>

project/GraveBooking/Views/viewGrave/adminProfile.cshtml
@model GraveBooking.Models.ViewModel
@{
    ViewBag.Title = "adminProfile";
}

<div class="card" style="background-color:lightgray;margin-left:100px;margin-right:100px">
    <h1 class="card-text" style="margin-bottom:20px;margin-top:20px;text-align:center">Admin Dashboard</h1>

    <div class="container">
        <div class="row">
            <div class="col" style="margin-left:150px">
                <div class="card" style="width:300px">
                    <img class="card-img-top" src="~/Media/Images/adminMenu/profile.png" alt="Card image">
                    <div class="card-body">
                        <center>
                             <a class="mt-auto" href="@Url.Action("updateAdminProfile","adminProfile")"><button class="btn btn-primary">Edit Profile</button></a>
                        </center>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="width:300px">
                    <img class="card-img-top" src="~/Media/Images/adminMenu/manage.png" alt="Card image">
                    <div class="card-body">
                        <center>
                            <a class="mt-auto" href="@Url.Action("DisplayGraveTable","viewGrave")"><button class="btn btn-primary">Manage Graves</button></a>
                        </center>
                    </div>
                </div>
            </div>

            <div class="w-100"></div>
            <div class="h-100"></div>

            <div class="col" style="margin-top:40px;margin-left:150px;margin-bottom:40px">
                <div class="card" style="width:300px">
                    <img class="card-img-top" src="~/Media/Images/adminMenu/add.png" alt="Card image">
                    <div class="card-body">
                        <center>
                            <a class="mt-auto" href="@Url.Action("addDescription","graveDescription")"><button class="btn btn-primary">Add Graveyard</button></a>
                        </center>
                    </div>
                </div>
            </div>
            <div class="col" style="margin-top:40px;margin-bottom:40px">
                <div class="card" style="width:300px">
                    <img class="card-img-top" src="~/Media/Images/adminMenu/search.png" alt="Card image">
                    <div class="card-body">
                        <center>
                            <a class="mt-auto" href="@Url.Action("viewOwnerInfo","viewOwnerInfo")"><button class="btn btn-primary">View Owners</button></a>
                        </center>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!--
<div class="col-md-12">
    <div class="col-md-1"></div>
    <div class="col-md-4">
        <center>
            <form id="form" class="f" action="//Url.Action(" adminProfile", "viewGrave" )" method="post">
                <div class="card">
                    <div class="card-body">
                        //foreach (var emp in Model.admins)
                        {
                        <img src="~/Media/Images/Users/default.png" alt="" class="img-fluid rounded-circle w-50 mb-3">
                        <h3>//emp.adminName</h3>
                        <h5>Edit Profile</h5>
                        <div class="mt-2" style="text-align: center"><a class="text-danger" href="@Url.Action("viewOwnerInfo", "viewOwnerInfo")">Owners list</a> </div>
                        <h5>Edit graves</h5>

                        }
                    </div>
                </div>
            </form>
        </center>
    </div>

    <div class="col-md-6"></div>
    <div class="col-md-1"></div>
</div>
-->

project/GraveBooking/Views/viewGrave/detailsPage.cshtml
@model GraveBooking.Models.ViewModel
@{
    ViewBag.Title = "detailsPage";
}
<div class="card">
    <div class="card-body">
            <div class="row">

                @foreach (var emp in Model.graveDescriptions)
                {
                    <div class="col-md-12">
                        <div>
                            <img src="@Url.Content(emp.posterImage)" runat="server" alt="@emp.graveyardName" style="width:1000px;margin-left:250px;margin-top:50px;height: 350px;">
                            <div class="mt-auto" style="width:300px;">

                                <h4 class="mt-2" style="width:1000px;margin-left:250px;text-align:center;">@emp.graveyardName</h4>

                                <h5 class="mt-2" style="width:1000px;margin-left:250px;text-align:center;">Plot capacity:@emp.numberOfPlots</h5>
                                <h5 class="mt-2" style="width:1000px;margin-left:250px;text-align:center;">Available Plot:@emp.availablePlot</h5>
                                <h5 class="mt-2" style="width:1000px;margin-left:250px;text-align:center;">Location:@emp.location</h5>
                                <h5 class="mt-2" style="width:1000px;margin-left:250px;text-align:center;">Contact No:@emp.contact</h5>
                                <h5 class="mt-2" style="width:1000px;margin-left:250px;text-align:center;">Plot Price:@emp.plotPrice taka</h5>
                              

                            </div>

                            <a class="mt-auto" href="@Url.Action("choosePlot", "ownerInfo")"><button class="buttonNormal" style="width:1000px;margin-left:250px;text-align:center;background:lightslategray;">Book a plot</button></a>

                            @{ Session["graveyardId"] = emp.graveyardId; }
                            @{ Session["MapLoc"] = emp.location; }


                        </div>
                    </div>
                }
            </div>
    </div>
</div>
                <div class="card">
                    <div class="card-body">
                        <center>
                            <div>

                                @{var id = Session["MapLoc"];}
                                <iframe width="1000" height="800" src="https://maps.google.com/maps?q=@id&output=embed"></iframe>

                            </div>
                        </center>
                    </div>
                </div>

          

project/GraveBooking/Views/viewGrave/updatePlotNo.cshtml
@{
    ViewBag.Title = "updatePlotNo";
}
<div class="col-md-12">
    <center>
        <h1>Booking successful</h1>
        <br />
        <a class="mt-auto" href="@Url.Action("viewGravePost", "viewGrave")"><button class="buttonNormal" style="width:1000px;margin-left:250px;text-align:center;background:lightslategray;">Return to homepage</button></a>
    </center>
</div>

project/GraveBooking/Views/viewGrave/viewGravePost.cshtml
@model GraveBooking.Models.ViewModel
@{
    ViewBag.Title = "viewGravePost";
}
<style>
    .wrapper {
        position: relative;
        display: inline-block;
        width: 100%;
    }

    img {
        width: 100%;
        height: auto;
    }

    .search-wrapper {
        position: absolute;
        align-items: center;
        top: 40%;
        left: 75%;
        padding: 15px;
        -ms-transform: translateX(-50%) translateY(-50%);
        -webkit-transform: translate(-50%,-50%);
        transform: translate(-50%,-50%);
    }

        .search-wrapper input {
            width: 100%;
        }
</style>

<div class="wrapper" style="margin-left:10px;margin-right:10px;margin-top:-80px">
    <nav class="navbar navbar-expand-md">

        <div class="col-md-12">
            <img src="~/Media/Images/homepage.png" alt="" class="rounded" style="margin-top:10px;height:500px;border-radius:50px">
            <form action="@Url.Action("viewGravePost","viewGrave")" method="post">
                <div class="search-wrapper">
                    <div class="input-group">
                        <input type="text" class="form-control" id="search_form" placeholder="Search" name="search" style=" position: absolute; width: 220px;height:40px;margin-left:20px; margin-top: 5px; padding: 18px; font-size: 25px;  border-top-left-radius: 8px; border-bottom-left-radius: 8px;background-color:white;border-color:lightslategray">
                        <div class="input-group-btn">
                            <button class="btn btn-default" id="navSearchBtn" type="submit" style="margin-top:5px;margin-left: 240px; background:lightslategray;width: 80px;height:40px; border-radius: 0 0 0 0; border-top-right-radius: 5px; border-bottom-right-radius: 5px;">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>

            </form>
        </div>

    </nav>
</div>


@foreach (var emp in Model.graveDescriptions)
{

    <nav class="navbar navbar-expand-md  mt-2">
        <div class="col-md-1">
        </div>
        <div class="col-md-5">

            <img src="@Url.Content(emp.posterImage)" runat="server" alt="@emp.graveyardName" style="width:500px;margin-top:50px;height: 350px;">
        </div>
        <div class="col-md-1">
        </div>
        <div class="col-md-4">

            <div class="mt-auto" style="width:300px;">
                <h4 class="mt-2" style="width: 300px; margin-left: 80px;text-align: center;color:white;">dfghertg</h4>
                <h4 class="mt-2" style="width: 300px; margin-left: 80px;text-align: center;color:white;">dfghertg</h4>
                <h4 class="mt-2" style="width: 300px; margin-left: 80px;text-align: center; ">@emp.graveyardName</h4>
                <h5 class="mt-2" style="width: 300px; margin-left: 80px; text-align: center;">Plot capacity:@emp.numberOfPlots</h5>
                <h5 class="mt-2" style="width: 300px; margin-left: 80px; text-align: center; ">Available Plot:@emp.availablePlot</h5>
                <h5 class="mt-2" style="width: 300px; margin-left: 80px; text-align: center; ">Location:@emp.location</h5>
                <h5 class="mt-2" style="width: 300px; margin-left: 80px; text-align: center; ">Contact No:@emp.contact</h5>

            </div>

            @{ /*Session["graveyardId"] = emp.graveyardId;*/ }

            <a class="mt-auto" href="@Url.Action("detailsPage", "viewGrave",new { id = @emp.graveyardId })"><button class="buttonNormal" style="width: 300px; margin-left: 80px; text-align: center;background: lightslategray;">View Details</button></a>


            @foreach (var ad in Model.admins.Where(i => i.adminId == emp.adminId))
            {
                <!-- <p class="text" style="text-align:center;color:blue;">Posted by <a class="text" href="" style="text-decoration: none;margin-left:30px;text-align:center;color: blue"></a></p>-->
            }
        </div>
        <div class="col-md-1">
        </div>
    </nav>

}