project/GraveBooking/Controllers/AdminauthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using GraveBooking.Models;
using GraveBooking.Services.Data;
using GraveBooking.Services.Operation;
using System.Collections.Specialized;
using System.IO;
using Microsoft.WindowsAPICodePack.Dialogs;

namespace GraveBooking.Controllers
{
    public class AdminauthenticationController : Controller
    {
        // GET: Adminauthentication
        public ActionResult adminLogin()
        {
            NameValueCollection request = Request.Form;
            string adminPhone, adminPassword;
            ViewBag.verification = false;
            if (!string.IsNullOrEmpty(request["adminPhone"]) && !string.IsNullOrEmpty(request["adminPassword"]))
            {
                adminPhone = request["adminPhone"];
                adminPassword = request["adminPassword"];
                admin admin = new admin();
                admin.adminPhone = adminPhone;
                admin.adminPassword = adminPassword;
              

                SecurityServices service = new SecurityServices();
                if (service.AuthenticateAdmin(admin))
                {
                    Session["admin"] = adminPhone;
                    SecurityDAO db = new SecurityDAO();
                   int count= db.loginCount(adminPhone);
                    int adminId = db.getAdminId(adminPhone,adminPassword);
                    Session["count"] = Convert.ToString(count);
                    count++;
                    Session["adminId"] = adminId;
                    db.updateCount(adminPhone,count);
                    
                    return RedirectToAction("adminProfile", "viewGrave");
                    


                }
                else
                {
                    ViewBag.verification = true;
                    return View();
                }
            }


            return View();
        }
        public ActionResult adminLogout()
        {
            Session.Abandon();
            Session.Clear();
            return RedirectToAction("LoginAs", "Home");
        }
        public ActionResult adminRegistration()
        {

            NameValueCollection request = Request.Form;
            string adminName, adminEmail, adminPhone, adminPassword;
            ViewBag.verification = false;
            if (!string.IsNullOrEmpty(request["adminName"]) && !string.IsNullOrEmpty(request["adminPhone"]) && !string.IsNullOrEmpty(request["adminPassword"]))
            {
                adminName = request["adminName"];
                adminEmail = request["adminEmail"];
                adminPhone = request["adminPhone"];
                adminPassword = request["adminPassword"];


                admin admin = new admin();
                admin.adminName = adminName;
                admin.adminEmail = adminEmail;
                admin.adminPhone = adminPhone;
                admin.adminPassword = adminPassword;
                SecurityDAO db = new SecurityDAO();
                SecurityServices service = new SecurityServices();

                int adminId = db.getAdminId(adminPhone, adminPassword);
                Session["adminId"] = adminId;

                if (service.AuthenticateAdmin(admin))
                {
                    ViewBag.verification = true;
                    return View();
                }
                else
                    db.createAdmin(admin);

                TaskDialog.Show("Admin Profile created successfully.You can sign in now");
                return RedirectToAction("adminLogin", "adminAuthentication");
                //return RedirectToAction("adminProfile", "viewGrave");
            }

            return View();
        }



    }
}

project/GraveBooking/Controllers/viewGraveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GraveBooking.Models;
using GraveBooking.Services.Data;
using System.Collections.Specialized;
using System.Dynamic;
using System.IO;

namespace GraveBooking.Controllers
{
    public class viewGraveController : Controller
    {
        // GET: viewGrave
        public ActionResult viewGravePost()
        {
            SecurityDAO dAO = new SecurityDAO();
            List<graveDescription> graveList = dAO.fetchgrave();
            List<admin> adminList = dAO.fetchAdmin();
            ViewModel allmodel = new ViewModel();
            allmodel.graveDescriptions = graveList;
            allmodel.admins = adminList;

            NameValueCollection request = Request.Form;
            string search;

            if (!string.IsNullOrEmpty(request["search"]))
            {
                search = request["search"];
                graveList = dAO.fetchgrave(search);
                allmodel.graveDescriptions = graveList;
                allmodel.admins = adminList;
                return View(allmodel);
            }
            return View(allmodel);
        }
        public ActionResult DisplayGraveTable()
        {
            int gId = 0;
            if (Session["adminId"] != null)
            {
                // Value is not null, read actual value from session
                gId = (int)Session["adminId"];
            }
            SecurityDAO dAO = new SecurityDAO();
            List<graveDescription> graveList = dAO.fetchgraveAsPerAdminId(gId);
            
            ViewModel allmodel = new ViewModel();
            allmodel.graveDescriptions = graveList;
            
            return View(allmodel);
        }
        public ActionResult adminProfile()
        {
            int adminId = 0;
            if (Session["adminId"] != null)
            {
                // Value is not null, read actual value from session
                adminId = (int)Session["adminId"];
            }

            SecurityDAO dAO = new SecurityDAO();
            List<graveDescription> graveList = dAO.fetchgrave();
            List<admin> adminList = dAO.fetchAdmin(adminId);
            ViewModel allmodel = new ViewModel();
            allmodel.graveDescriptions = graveList;
            allmodel.admins = adminList;

            NameValueCollection request = Request.Form;
            string search;

            if (!string.IsNullOrEmpty(request["search"]))
            {
                search = request["search"];
                graveList = dAO.fetchgrave(search);
                allmodel.graveDescriptions = graveList;
                allmodel.admins = adminList;
                return View(allmodel);
            }
            
            return View(allmodel);
        }

        public ActionResult detailsPage()
        {
            string id = Request.Url.Segments.Last();
            int gId = Convert.ToInt32(id);
         /*   if (Session["graveyardId"] != null)
            {
                // Value is not null, read actual value from session
                gId = (int)Session["graveyardId"];
            }*/
            SecurityDAO dAO = new SecurityDAO();
            dAO.DeleteTempData();
            var list1 = new List<string>();
            list1 = dAO.fetchBookedPlots(gId);
            dAO.addUnbookedPlots(list1);
            List<graveDescription> graveList = dAO.fetchgrave(gId);
            
            ViewModel allmodel = new ViewModel();
            allmodel.graveDescriptions = graveList;

            Session["graveyardId"] = gId;
            return View(allmodel);
        }

        public ActionResult OwnerInfoIntermediate()
        {
            int gId = 0;
            if (Session["graveyardId"] != null)
            {
                // Value is not null, read actual value from session
                gId = (int)Session["graveyardId"];
            }
            SecurityDAO dAO = new SecurityDAO();
            dAO.DeleteTempData();
            var list1 = new List<string>();
            list1 = dAO.fetchBookedPlots(gId);
            dAO.addUnbookedPlots(list1);
            List<Temp> plotList = dAO.showUnbookedPlots();
            ViewModel allmodel = new ViewModel();
            allmodel.Temps = plotList;
            return View(allmodel);

        }
        public ActionResult updatePlotNo()
        {
            int gId = 0;
            if (Session["graveyardId"] != null)
            {
                // Value is not null, read actual value from session
                gId = (int)Session["graveyardId"];
            }
            
            string id = Request.Url.Segments.Last();
            int pId = Convert.ToInt32(id);
            SecurityDAO dao = new SecurityDAO();
           
            int available = dao.getAvailableNoOfPlots(gId);
            int cnt = dao.getPlotCount(gId);
            dao.updateAvailablePlots(gId, cnt, available);
            dao.updatePlotNoInBooking(pId);
            dao.updatePlotNoInOwner(pId);

            return View();


        }

    }
}

project/GraveBooking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")

</head>
<body>

    <div class="sticky" style="background:gainsboro;border-bottom:thin;border-bottom-color:black">
        <nav class="navbar navbar-expand-md  mt-2">
            <div class="col-md-6">
                <div class="intro" style="background:gainsboro;color:darkslategray;font-size:35px;margin:5px 5px 5px 5px;font-weight: bold;">
                    <p>
                        GravePlot Booking Website
                    </p>
                </div>
            </div>
            <div class="col-md-6">
                <ul>
                    <style>
                        nav ul li a.active,nav ul li a:hover {
                            color:white;
                            background: gray;
                            transition: 0.5s;
                            text-decoration: none;
                        }
                    </style>
                    <li style="display: inline-block; line-height: 80px; padding: 0; margin: 0 5px; text-decoration: none; list-style: none; box-sizing: border-box;"><a style="color:darkslategray;font-size:17px;padding:7px 13px;border-radius:3px;text-transform:uppercase; " href="@Url.Action("viewGravePost", "viewGrave")">Home</a></li>
                    <li style="display: inline-block; line-height: 80px; padding: 0; margin: 0 5px; text-decoration: none; list-style: none; box-sizing: border-box;"><a style="color:darkslategray;font-size:17px;padding:7px 13px;border-radius:3px;text-transform:uppercase;" href="@Url.Action("Contact", "Home")">Contact</a></li>
                    <li style="display: inline-block; line-height: 80px; padding: 0; margin: 0 5px; text-decoration: none; list-style: none; box-sizing: border-box;"><a style="color:darkslategray;font-size:17px;padding:7px 13px;border-radius:3px;text-transform:uppercase;" href="@Url.Action("About", "Home")">About Us</a></li>
                   
                    @if (Session["admin"] != null)
                    {
                        <li style="display: inline-block; line-height: 80px; padding: 0; margin: 0 5px; text-decoration: none; list-style: none; box-sizing: border-box;"><a style="color:darkslategray;font-size:17px;padding:7px 13px;border-radius:3px;text-transform:uppercase; " href="@Url.Action("adminProfile", "viewGrave")">Menu</a></li>
                        <li style="display: inline-block; line-height: 80px; padding: 0; margin: 0 5px; text-decoration: none; list-style: none; box-sizing: border-box;"><a style="color:darkslategray;font-size:17px;padding:7px 13px;border-radius:3px;text-transform:uppercase; " href="@Url.Action("adminLogout", "Adminauthentication")">Sign Out</a></li>
                    }

                    else if (Session["Users"] != null)
                    {
                        <li style="display: inline-block; line-height: 80px; padding: 0; margin: 0 5px; text-decoration: none; list-style: none; box-sizing: border-box;"><a style="color:darkslategray;font-size:17px;padding:7px 13px;border-radius:3px;text-transform:uppercase; " href="@Url.Action("UserProfile", "Home")">Menu</a></li>

                        <li style="display: inline-block; line-height: 80px; padding: 0; margin: 0 5px; text-decoration: none; list-style: none; box-sizing: border-box;"><a style="color:darkslategray;font-size:17px;padding:7px 13px;border-radius:3px;text-transform:uppercase; " href="@Url.Action("Logout", "Authentication")">Sign Out</a></li>

                    }
                    else
                    {
                        <li style="display: inline-block; line-height: 80px; padding: 0; margin: 0 5px; text-decoration: none; list-style: none; box-sizing: border-box;"><a style="color:darkslategray;font-size:17px;padding:7px 13px;border-radius:3px;text-transform:uppercase;" href="@Url.Action("LoginAs", "Home")">Sign In</a></li>
                    }
                </ul>
            </div>
        </nav>

    </div>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />



    @RenderBody()


    <footer class="page-footer bg-dark mt-5">
        &nbsp;

        <div class="container text-center text-md-left mt-5">
            <div class="row">
                <div class="col-md-3 mx-auto mb-4">
                    <h6 class="text-uppercase font-weight-bold" style="color:lightblue;">About Us</h6>
                    &nbsp;
                    <p class="text-white"><a class="text-white" href="" style="text-decoration: none;">Privacy Policy</a></p>
                    <p class="text-white"><a class="text-white" href="" style="text-decoration: none;">Cookie Policy</a></p>
                    <p class="text-white"><a class="text-white" href="" style="text-decoration: none;">Terms & Condtions</a></p>
                </div>

                <div class="col-md-2 mx-auto mb-4">
                    <h6 class="text-uppercase font-weight-bold" style="color:lightblue;">Address</h6>
                    &nbsp;
                    <p class="mt-2 text-white">#Plot 23, #Block D, Road 12, Purbachol, Dhaka</p>

                </div>
                <div class="col-md-2 mx-auto mb-4">
                    <h6 class="text-uppercase font-weight-bold" style="color:lightblue;">Contact</h6>
                    &nbsp;
                    <p class="text-white"><a class="text-white" href="" style="text-decoration: none;">+880 8734 986</a></p>
                    <p class="text-white"><a class="text-white" href="" style="text-decoration: none;">+880 3458 653</a></p>

                </div>
                <div class="col-md-3 mx-auto mb-4">
                    <h6 class="text-uppercase font-weight-bold" style="color:lightblue;">Follow Us</h6>
                    &nbsp;
                    <p class="text-white"><a class="text-white" href="" style="text-decoration: none;">www.graveplot.7.com/page/097654456</a></p>
                    <p class="text-white"><a class="text-white" href="" style="text-decoration: none;">https://grave_plot_77</a></p>

                </div>

            </div>
        </div>

        <div class="footer-copyright text-center text-white py-3 mr-3">
            <p class="h6">&copy;Copyright <a class="text-white font-weight-bold" href="#">GravePlot Booking Website</a></p>
            <p>Designed By tamanna, muniya & tahiya</p>

        </div>


    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>